#!/bin/bash
#
#  =========================
#  
#  Copyright (C) 2019-2020 TenSeventy7
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#  
#  =========================
#  

TOOLCHAIN=$(pwd)/toolchain/arm-eabi-4.8-ubertc
TOOLCHAIN_EXT=$(pwd)/toolchain/arm-eabi-4.8-ubertc
DTBTOOL=$(pwd)/tools/dtbTool

DEVICE_BUILD=`echo $1 | tr 'A-Z' 'a-z'`
CONFIG_DIR=$(pwd)/arch/arm/configs
OUTPUT_DIR=$(pwd)/output
BUILDDATE=$(date +%s)

FILE_OUTPUT=ArKernel_${DEVICE_BUILD}_ci_${BUILDDATE}.zip

script_echo() {
	echo "  $1"
}

exit_script() {
	kill -INT $$
}

make_output() {
	if [[ ! -d "${OUTPUT_DIR}" ]]
	then
	    mkdir ${OUTPUT_DIR}
	fi

	if [[ ! -d "${DEIVCE_OUTPUT_DIR}" ]]
	then
	    mkdir ${DEIVCE_OUTPUT_DIR}
	fi

	if [[ ! -d "$(pwd)/releases" ]]
	then
	    mkdir $(pwd)/releases
	fi
}

define_variant() {
	DEVICE_VARIANT=msm8916_sec_${DEVICE_BUILD}
	VARIANT_DEFCONFIG=${DEVICE_VARIANT}_defconfig

	DEIVCE_OUTPUT_DIR=${OUTPUT_DIR}/${DEVICE_BUILD}
	FILE_OUTPUT=ArKernel_${DEVICE_BUILD}_ci_${BUILDDATE}.zip

	make_output
	make -C $(pwd) O=${DEIVCE_OUTPUT_DIR} VARIANT_DEFCONFIG=$VARIANT_DEFCONFIG msm8916_sec_defconfig SELINUX_DEFCONFIG=selinux_defconfig

}

build_dtb() {
	$(pwd)/tools/dtbTool -o ${DEIVCE_OUTPUT_DIR}/arch/arm/boot/dt.img -s 2048 -p ${DEIVCE_OUTPUT_DIR}/scripts/dtc/ ${DEIVCE_OUTPUT_DIR}/arch/arm/boot/dts/
}

build_kernel() {
	make -C $(pwd) O=${DEIVCE_OUTPUT_DIR}
	cp `find ${DEIVCE_OUTPUT_DIR} -iname *.ko` $(pwd)/anykernel/modules/system/lib/modules -rf
	mkdir $(pwd)/anykernel/modules/system/lib/modules/pronto
	cp $(pwd)/anykernel/modules/system/lib/modules/wlan.ko $(pwd)/anykernel/modules/system/lib/modules/pronto/pronto_wlan.ko -f
}

ak_compose_manifest() {
	MANIFEST_TOP=`cat $(pwd)/tools/ak/.manifest-top`
	MANIFEST_BOTTOM=`cat $(pwd)/tools/ak/.manifest-bottom`

	touch $(pwd)/anykernel/device.ark.sh
	echo "${MANIFEST_TOP}" > $(pwd)/anykernel/device.ark.sh
	echo "device.name1=${DEVICE_BUILD}" >> $(pwd)/anykernel/device.ark.sh
	echo "device.name2=lineage_${DEVICE_BUILD}" >> $(pwd)/anykernel/device.ark.sh
	echo "device.name3=dot_${DEVICE_BUILD}" >> $(pwd)/anykernel/device.ark.sh
	echo "device.name4=aosp_${DEVICE_BUILD}" >> $(pwd)/anykernel/device.ark.sh
	echo "device.name5=pa_${DEVICE_BUILD}" >> $(pwd)/anykernel/device.ark.sh
	echo "device.name6=fortuna3g" >> $(pwd)/anykernel/device.ark.sh
	echo ${MANIFEST_BOTTOM} >> $(pwd)/anykernel/device.ark.sh
}

build_zip() {
	mv ${DEIVCE_OUTPUT_DIR}/arch/arm/boot/zImage $(pwd)/anykernel/zImage -f
	mv ${DEIVCE_OUTPUT_DIR}/arch/arm/boot/dt.img $(pwd)/anykernel/Image.gz-dtb -f
	ak_compose_manifest
	cd $(pwd)/anykernel
	zip -9 -r ./${FILE_OUTPUT} ./*
	mv ./${FILE_OUTPUT} ./../releases/${FILE_OUTPUT}
}

build_kernel_full() {
	define_variant
	build_kernel
	build_dtb
	build_zip
}

DEVICE_BUILD=fortunave3g
build_kernel_full

DEVICE_BUILD=fortuna3g
build_kernel_full
