ccflags-y += -Idrivers/media/platform/msm/camera_v2_grandmax
ccflags-y += -Idrivers/media/platform/msm/camera_v2_grandmax/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_grandmax/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
